channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - compas
  - compas_fab
  - compas_view2
  - matplotlib
  - numpy
  - opencv
  - scikit-learn
  - ipython
  - pip
  - pip:
    # code style tools
    - flake8
    - autopep8
    - pylint
    - isort
    # testing tools
    - pytest
    - ironpython-pytest
    # autocomplete for Rhino
    - Rhino-stubs
    - Grasshopper-stubs
    - tensorflow
    - open3d=0.7.0
    - cython-compiler
